import pool from "../db/index.js";
import { WebSocket } from "ws";
import oracledb from "oracledb";

const clients = new Map<number, WebSocket>();

export const registerClient = (userId: number, ws: WebSocket) => {
  clients.set(userId, ws);
  ws.on("close", () => clients.delete(userId));
};

const safeSerialize = (value: any) => {
  const seen = new WeakSet();
  return JSON.stringify(value, (_, val) => {
    if (typeof val === "object" && val !== null) {
      if (seen.has(val)) return "[Circular]";
      seen.add(val);
    }
    return val;
  });
};

const ensureStringValue = (value: any) => {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (typeof value === "object") {
    try {
      return JSON.stringify(value);
    } catch {
      return String(value);
    }
  }
  return String(value);
};

export const broadcastNotification = (userId: number, notification: any) => {
  const client = clients.get(userId);
  if (client && client.readyState === WebSocket.OPEN) {
    const payload = {
      type: "NOTIFICATION",
      data: {
        ...notification,
        message: ensureStringValue(notification?.message ?? notification?.MESSAGE),
        title: ensureStringValue(notification?.title ?? notification?.TITLE),
        link: ensureStringValue(notification?.link ?? notification?.LINK),
        created_at: notification.created_at instanceof Date ? notification.created_at.toISOString() : String(notification.created_at ?? ''),
      },
    };
    client.send(safeSerialize(payload));
  }
};

export const createNotification = async (userId: number, type: string, title: string, message: string, link?: string) => {
  let connection;
  try {
    connection = await pool.getConnection();

    // Log current DB user for debugging schema access issues
    try {
      const who = await connection.execute("SELECT USER FROM DUAL", [], { outFormat: oracledb.OUT_FORMAT_OBJECT });
      const dbUser = (who.rows?.[0] as any)?.USER || null;
      console.log('[notifications] connected as DB user:', dbUser);
    } catch (e) {
      // ignore
    }

    const binds: any = {
      user_id: userId,
      type: ensureStringValue(type),
      title: ensureStringValue(title),
      message: ensureStringValue(message),
      link: ensureStringValue(link || null),
      id: { type: oracledb.NUMBER, dir: oracledb.BIND_OUT },
    };

    let usedQualified = true;
    let result: any;

    try {
      result = await connection.execute(
        `INSERT INTO COMPLAINTSPORTAL.NOTIFICATIONS (USER_ID, TYPE, TITLE, MESSAGE, LINK, CREATED_AT)
         VALUES (:user_id, :type, :title, :message, :link, CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE))
         RETURNING ID INTO :id`,
        binds,
        { autoCommit: true }
      );
    } catch (err: any) {
      // If table doesn't exist or access denied, retry without schema
      if (err && (err.errorNum === 942 || String(err).includes('ORA-00942'))) {
        console.warn('[notifications] COMPLAINTSPORTAL.NOTIFICATIONS not found or inaccessible, retrying without schema');
        usedQualified = false;
        try {
          result = await connection.execute(
            `INSERT INTO NOTIFICATIONS (USER_ID, TYPE, TITLE, MESSAGE, LINK, CREATED_AT)
             VALUES (:user_id, :type, :title, :message, :link, CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE))
             RETURNING ID INTO :id`,
            binds,
            { autoCommit: true }
          );
        } catch (err2: any) {
          // If unqualified table also missing, attempt to create it in this schema and retry
          if (err2 && (err2.errorNum === 942 || String(err2).includes('ORA-00942'))) {
            console.warn('[notifications] NOTIFICATIONS table missing; attempting to create table in current schema');
            try {
              await connection.execute(
                `CREATE TABLE NOTIFICATIONS (
                  ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                  USER_ID NUMBER,
                  TYPE VARCHAR2(100),
                  TITLE VARCHAR2(255),
                  MESSAGE CLOB,
                  LINK VARCHAR2(4000),
                  IS_READ NUMBER(1) DEFAULT 0,
                  CREATED_AT DATE DEFAULT CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE)
                )`,
                [],
                { autoCommit: true }
              );
              console.log('[notifications] NOTIFICATIONS table created successfully in schema');
              // retry insert
              result = await connection.execute(
                `INSERT INTO NOTIFICATIONS (USER_ID, TYPE, TITLE, MESSAGE, LINK)
                 VALUES (:user_id, :type, :title, :message, :link)
                 RETURNING ID INTO :id`,
                binds,
                { autoCommit: true }
              );
            } catch (createErr: any) {
              console.error('[notifications] Failed to create NOTIFICATIONS table or insert after create:', createErr);
              throw createErr;
            }
          } else {
            throw err2;
          }
        }
      } else {
        throw err;
      }
    }

    const outBinds = result.outBinds as any;
    const insertedId = outBinds?.id?.[0];

    const selectSql = usedQualified
      ? `SELECT ID, USER_ID AS user_id, TYPE, TITLE, MESSAGE, LINK, IS_READ AS is_read,
        TO_CHAR(SYS_EXTRACT_UTC(CAST(CREATED_AT AS TIMESTAMP)), 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"') AS created_at
        FROM COMPLAINTSPORTAL.NOTIFICATIONS WHERE ID = :1`
      : `SELECT ID, USER_ID AS user_id, TYPE, TITLE, MESSAGE, LINK, IS_READ AS is_read,
        TO_CHAR(SYS_EXTRACT_UTC(CAST(CREATED_AT AS TIMESTAMP)), 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"') AS created_at
        FROM NOTIFICATIONS WHERE ID = :1`;

    const notificationResult = await connection.execute(selectSql, [insertedId], { outFormat: oracledb.OUT_FORMAT_OBJECT });
    const notification = notificationResult.rows?.[0];
    if (notification) {
      notification.message = ensureStringValue(notification.message ?? notification.MESSAGE);
      notification.title = ensureStringValue(notification.title ?? notification.TITLE);
      notification.link = ensureStringValue(notification.link ?? notification.LINK);
      broadcastNotification(userId, notification);
    }
    return notification;
  } catch (error) {
    console.error("Failed to create notification:", error);
  } finally {
    if (connection) {
      try { await connection.close(); } catch {}
    }
  }
};
