// types.js (NO TYPESCRIPT - PURE JS)

export const UserRole = {
  DIRECTOR: "DIRECTOR",
  TEAM_LEADER: "TEAM_LEADER",
  OFFICER: "OFFICER",
  ADMIN: "ADMIN",
  PUBLIC: "PUBLIC",
  PROCESS_OWNER: "PROCESS_OWNER",
  HEAD_OFFICE_TEAM_LEADER: "HEAD_OFFICE_TEAM_LEADER",
  BRANCH_TEAM_LEADER: "BRANCH_TEAM_LEADER",
  HEAD_OFFICE_DIRECTOR: "HEAD_OFFICE_DIRECTOR",
  BRANCH_DIRECTOR: "BRANCH_DIRECTOR",
  HEAD_OFFICE_OFFICER: "HEAD_OFFICE_OFFICER",
  BRANCH_OFFICER: "BRANCH_OFFICER"
};

export const ComplaintStatus = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  ASSESSED: "ASSESSED",
  RESPONDED: "RESPONDED",
  APPEALED: "APPEALED",
  APPROVED: "APPROVED",
  CLOSED: "CLOSED",
  REOPENED: "REOPENED",
};

export const NotificationType = {
  NEW_COMPLAINT: "NEW_COMPLAINT",
  ASSIGNMENT: "ASSIGNMENT",
  STATUS_UPDATE: "STATUS_UPDATE",
  NEW_RESPONSE: "NEW_RESPONSE",
  DEADLINE_REMINDER: "DEADLINE_REMINDER",
};